/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.UsuariosController;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Capacitacion5
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        setLocationRelativeTo(null);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelUser = new javax.swing.JLabel();
        LabelPass = new javax.swing.JLabel();
        FieldUser = new javax.swing.JTextField();
        FieldPass = new javax.swing.JPasswordField();
        JCheckPass = new javax.swing.JCheckBox();
        BtnLogIn = new javax.swing.JButton();
        BtnRegistrarse = new javax.swing.JButton();
        LabelLujanLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oficina De Empleo LogIn");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LabelUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-persona-de-sexo-masculino-64.png"))); // NOI18N
        LabelUser.setText("Usuario");

        LabelPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-candado-2-64.png"))); // NOI18N
        LabelPass.setText("Contraseña");

        FieldUser.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        FieldPass.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        FieldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldPassKeyPressed(evt);
            }
        });

        JCheckPass.setBackground(new java.awt.Color(255, 255, 255));
        JCheckPass.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        JCheckPass.setText("Mostrar Contraseña");
        JCheckPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCheckPassActionPerformed(evt);
            }
        });

        BtnLogIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-entrar-64.png"))); // NOI18N
        BtnLogIn.setText("Log In");
        BtnLogIn.setBorder(null);
        BtnLogIn.setBorderPainted(false);
        BtnLogIn.setContentAreaFilled(false);
        BtnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogInActionPerformed(evt);
            }
        });

        BtnRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-llave-64.png"))); // NOI18N
        BtnRegistrarse.setText("Registrarse");
        BtnRegistrarse.setBorder(null);
        BtnRegistrarse.setBorderPainted(false);
        BtnRegistrarse.setContentAreaFilled(false);
        BtnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarseActionPerformed(evt);
            }
        });

        LabelLujanLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/marca_lujan_004.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BtnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FieldPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(FieldUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(JCheckPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(BtnLogIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelLujanLogo)
                .addGap(164, 164, 164))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LabelLujanLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUser)
                    .addComponent(FieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPass)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(FieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(JCheckPass)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLogIn)
                    .addComponent(BtnRegistrarse))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCheckPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCheckPassActionPerformed

        if (JCheckPass.isSelected() == true) {
            FieldPass.setEchoChar((char) 0);
        } else {
            FieldPass.setEchoChar('*');
        }
    }//GEN-LAST:event_JCheckPassActionPerformed

    private void BtnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogInActionPerformed
    String password = new String (FieldPass.getPassword());
    UsuariosController.Login(FieldUser.getText(), FieldPass.getText());
    





//    String user = "admin";
//    String pass = "1234";
//    
//    if (FieldUser.getText().equals(user) && FieldPass.getText().equals(pass)){
//        dispose();
//        new MenuPrincipal().setVisible(true);
//    }else{
//        Icon ico = new ImageIcon(getClass().getResource("/Imagenes/icons8-administrador-hombre-2-64.png"));
//        JOptionPane.showMessageDialog(null, "Credenciales Incorrectas","Error Clave/Usuario", JOptionPane.INFORMATION_MESSAGE, ico);
//    }
        
    }//GEN-LAST:event_BtnLogInActionPerformed

    private void BtnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarseActionPerformed
      AbrirVentanaUserCreate();
   
    }//GEN-LAST:event_BtnRegistrarseActionPerformed

    private void FieldPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldPassKeyPressed
  
    }//GEN-LAST:event_FieldPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogIn;
    private javax.swing.JButton BtnRegistrarse;
    private javax.swing.JPasswordField FieldPass;
    private javax.swing.JTextField FieldUser;
    private javax.swing.JCheckBox JCheckPass;
    private javax.swing.JLabel LabelLujanLogo;
    private javax.swing.JLabel LabelPass;
    private javax.swing.JLabel LabelUser;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

  

    private void AbrirVentanaUserCreate() {
        dispose();
       new UserCreate().setVisible(true);
    }
}
